app/Aviso.php, app/Http/Controllers/AvisoController.php, database/migrations/2020_04_23_004544_create_avisos_table.php, resources/views/avisos/form.blade.php, resources/views/avisos/index.blade.php, resources/views/avisos/show.blade.php
guarded, função sets e gets data, card nas blades view index, show e form
=> Interação nº5

app/Http/Controllers/ConvenioController.php, resources/views/convenios/partials/index.blade.php, resources/views/convenios/show.blade.php
Tive dificuldade com o posicionamento dos botões no view show
=> parte 6 - metodo delete

app/Http/Controllers/EstagioController.php, resources/views/estagios/partials/index.blade.php, routes/web.php
envio um pouco atrasado depois que ficar quase um dia parado com um problema na rota delete, mas deve funcionar agora
=> estagio parte 6

app/Estagio.php, app/Http/Controllers/EstagioWorkflowController.php, app/Http/Requests/EstagioRequest.php, config/workflow.php, database/factories/EstagioFactory.php, database/migrations/2020_04_24_045952_create_estagios_table.php, database/seeds/EstagioSeeder.php, resources/views/estagios/etapas.blade.php, resources/views/estagios/form.blade.php, resources/views/estagios/partials/em_analise_academica.blade.php, resources/views/estagios/partials/em_analise_alteracao.blade.php, resources/views/estagios/partials/em_analise_tecnica.blade.php, resources/views/estagios/partials/index.blade.php, resources/views/estagios/show.blade.php, routes/web.php
É possível que eu tenha passado por cima de algum detalhe ou errado alguma posição, principalmente porque foi extremamente confuso trabalhar com tanto campo de alteração com pouca diferença de nome.
Iniciei o workflow de rescisão, mas não fiz tudo pois não sei ao certo como vai funcionar, principalmente por possuirem campos de migrations diferentes das outras migrations
=> Continuação do workflow

app/Estagio.php, app/Http/Controllers/EstagioController.php, resources/views/estagios/index.blade.php
uma pequena questão é que não tive muita ideia de como colocar um old, até por não ser um radio, ficava visualmente quebrado, e nem um campo string que desse para fazer isso mais facilmente, e recuperar um option da raiz Estagio também é complicado, até pela diferença do label de cada select usuario e do real nome de entrada na base de dados
=> filtro de status na busca

app/Http/Requests/ConvenioRequest.php, app/Http/Requests/EmpresaRequest.php, public/js/convenios.js, public/js/empresas.js, resources/views/convenios/form.blade.php, resources/views/empresas/form.blade.php
tirei a validação por DDD para poder inserir números de celular, mas coloquei algumas condições nos campos de telefone pra que haja uma checagem mínima.
=> mudanças na identificação do telefone

app/Http/Controllers/EstagioWorkflowController.php, app/Http/Controllers/PDFsController.php, app/Http/Requests/EstagioRequest.php, database/migrations/2020_08_27_172729_changes_estagios_fields_to_nullable.php, database/migrations/2020_09_02_095710_update_estagios_fields.php, database/migrations/2020_09_02_111626_newupdates_fields_estagios.php, database/seeds/EstagioSeeder.php, resources/views/emails/login_empresa.blade.php, resources/views/empresas/form.blade.php, resources/views/empresas/show.blade.php, resources/views/estagios/etapas.blade.php, resources/views/login/empresa.blade.php, resources/views/pdfs/fflch.blade.php, resources/views/pdfs/parecer.blade.php, resources/views/pdfs/renovacao.blade.php, resources/views/pdfs/termo.blade.php
Gerador de Parecer adcionado e estruturado, o unico problema é que fatam duas variaveis no gerador de pdf "parecer" na área de <b> PROFESSOR - Nº USP DO PROFESSOR </b> para colocar no ar, as quais eu estou com um pouco de dificuldade pra realizar
=> Correções estruturais do gerador de pdf e mudança nos emails das empresas

app/Estagio.php, app/Http/Controllers/EstagioController.php, app/Http/Controllers/EstagioWorkflowController.php, app/Http/Controllers/PDFsController.php, app/Http/Requests/EmpresaRequest.php, config/laravel-usp-theme.php, database/factories/EmpresaFactory.php, database/migrations/2020_09_03_105738_newupdates_pareceristas_fields_estagios.php, database/migrations/2020_09_03_115908_newupdates_fields_empresas.php, database/seeds/EmpresaSeeder.php, public/js/estagios.js, resources/views/empresas/form.blade.php, resources/views/empresas/show.blade.php, resources/views/estagios/form.blade.php, resources/views/estagios/partials/em_analise_academica.blade.php, resources/views/estagios/partials/index.blade.php, resources/views/estagios/partials/rescisao.blade.php, resources/views/estagios/show.blade.php, resources/views/pdfs/convenio.blade.php, resources/views/pdfs/fflch.blade.php, resources/views/pdfs/parecer.blade.php, resources/views/pdfs/renovacao.blade.php, resources/views/pdfs/rescisao.blade.php, resources/views/pdfs/termo.blade.php, routes/web.php
- Gerador de PDF de rescisão funcional e modificação no gerador de parecer
- Deferimento Parcial e Condições extras adcionadas
- Novo campo de E-mail de contato da empresa
- Alterações de formatação dos geradores de pdf de renovação e termo de ciência
- Pareceristas podem visualizar os estagios os quais deram parecer
=> Correções e funções adcionadas

app/Http/Controllers/PDFsController.php, app/Mail/enviar_para_analise_tecnica_mail.php, app/Mail/enviar_para_parecerista_mail.php, resources/views/emails/enviar_para_parecerista.blade.php, resources/views/pdfs/aditivo.blade.php, resources/views/pdfs/convenio.blade.php, routes/web.php
- Pequenas mudanças no envio de emai lde parecer
- Geradores de PDFs de Convénio e de aditivo funcionais
=> Formulários funcionais

app/Http/Requests/EmpresaRequest.php, app/Http/Requests/EstagioRequest.php, database/factories/EmpresaFactory.php, database/factories/EstagioFactory.php, database/migrations/2020_09_29_112942_drop_fields_empresas.php, database/migrations/2020_09_29_114501_new_estagios_fields_from_empresas.php, database/seeders/EmpresaSeeder.php, database/seeders/EstagioSeeder.php, resources/views/empresas/form.blade.php, resources/views/empresas/show.blade.php, resources/views/estagios/etapas.blade.php, resources/views/estagios/form.blade.php, resources/views/estagios/partials/gerenciar_parecerista.blade.php, resources/views/estagios/show.blade.php, resources/views/pdfs/renovacao.blade.php, resources/views/pdfs/termo.blade.php
-Opções de visualização e envio de emails com parecer e termos restrita apenas ao administrador
-Campos anteriormente pertencentes a tabela de empresa foram movidos para tabela de estágio, estes relativos ao contato e supervisor do estágio
=> Novos Updates

app/Http/Controllers/EstagioWorkflowController.php, public/js/estagios.js, resources/views/empresas/index.blade.php, resources/views/estagios/etapas.blade.php, routes/web.php
- Coluna de supervisor de estágio removida de empresas
- Botão para o administrador retornar estágio do perecer de mérito para análise técnica
=> Botão de retorno e remoção de coluna

app/Http/Controllers/EstagioWorkflowController.php, app/Models/Estagio.php, config/workflow.php, resources/views/estagios/etapas.blade.php, resources/views/estagios/partials/assinatura.blade.php, resources/views/estagios/partials/em_analise_tecnica.blade.php, routes/web.php
Esta etapa ainda não tem nenhuma função específica no momento, mas já funciona para categorização e controle.
=> Etapa de Workflow de Assinatura

app/Http/Controllers/FileController.php, app/Http/Requests/FileRequest.php, resources/lang/en/validation.php, resources/views/emails/enviar_para_analise_tecnica.blade.php, resources/views/emails/enviar_para_analise_tecnica_renovacao.blade.php, resources/views/estagios/etapas.blade.php, resources/views/estagios/partials/jupiter.blade.php, resources/views/estagios/partials/rescisao.blade.php, resources/views/estagios/show.blade.php, resources/views/files/partials/form.blade.php, resources/views/vagas/index.blade.php
-Atualização de autorização para gerar rescisão
-Arquivos visíveis para os pareceristas
-Aviso de limite de peso de arquivo adcionado
-Nomes dos dias da semana regularizados no partial Jupiter
-Texto dos emails atualizado para informar a necessidade de assinatura e retorno
=> Atualizações

app/Http/Controllers/PDFsController.php, public/js/estagios.js, resources/views/empresas/show.blade.php, resources/views/estagios/create.blade.php, resources/views/estagios/form.blade.php, resources/views/estagios/partials/em_elaboracao.blade.php, resources/views/estagios/partials/gerenciar_parecerista.blade.php, resources/views/estagios/partials/rescisao.blade.php
- Gerador de PDF temporariamente revertido para download ao invês de visualização
- Geradores de PDF disponíveis na etapa de rescisão
- Avisos sobre o período de entrega do termo adcionados
=> Atualizações rescisão e PDF

app/Http/Controllers/EstagioWorkflowController.php, resources/views/estagios/partials/cancelado.blade.php, routes/web.php
- Retirada do EstagioRequest, já que a etapa de alteração não tem mais formulário
- Hábilidade do administrador voltar do cancelamento em caso de cancelamento acidental
=> novas correções: alteração e cancelamento

app/Http/Controllers/EstagioWorkflowController.php, resources/views/estagios/partials/concluido.blade.php, resources/views/files/partials/form.blade.php
- Envio de emails automático desativado na passagem pra etapa do parecer técnico
- reposicionamento das ações na etapa concluido
- pareceres de alteração voltam a retornar para parecer técnico, não para a etapa concluido
=> novas correções: etapa pós alteração e envio automático de emails

app/Http/Controllers/EstagioWorkflowController.php, app/Http/Controllers/PareceristaController.php, config/laravel-usp-theme.php, resources/views/emails/alteracao.blade.php, resources/views/estagios/partials/assinatura.blade.php, resources/views/estagios/partials/concluido.blade.php, resources/views/estagios/partials/em_alteracao.blade.php, resources/views/estagios/partials/gerenciar_parecerista.blade.php, resources/views/pdfs/aditivo.blade.php, resources/views/pdfs/parecer.blade.php, routes/web.php
Alterações no sistema:
- Retirada da necessidade de justificativa de renovação
- Opção no menu de pareceristas para visualizar estágios rescindidos
- Retirada a via do estágiario do pdf de parecer de mérito
=> correção de exibição das variaveis de alteração

app/Http/Controllers/EmailController.php, app/Mail/alteracao_empresa_mail.php, resources/views/emails/alteracao_empresa.blade.php, resources/views/estagios/partials/gerenciar_parecerista.blade.php, routes/web.php
email automático de alterações para a empresa
=> email automático de alterações para a empresa

app/Http/Controllers/Auth/LoginEmpresaController.php, app/Http/Controllers/EmailController.php, app/Http/Controllers/EmpresaController.php, app/Http/Controllers/EstagioController.php, app/Http/Controllers/EstagioWorkflowController.php, app/Http/Controllers/FileController.php, app/Http/Controllers/PareceristaController.php, resources/views/emails/enviar_analise_academica.blade.php, resources/views/emails/enviar_para_parecerista.blade.php, resources/views/estagios/etapas.blade.php, resources/views/estagios/index.blade.php, resources/views/estagios/partials/index.blade.php, resources/views/index.blade.php, resources/views/pdfs/parecer.blade.php
- Ajuste da visualização para colunas na Home
- Remoção do arquivo no Storage
- Limpeza de CNPJ na pesquisa
- Troca do Metodo de envio de email de Send pra Queue
- Acerto variaveis de chamada de parecerista
- Remoção de todos os registros extras em caso de exclusão de estágio (aditivos e arquivos)
- Pesquisa de estagiarios por nome e ordenação automática alfabética do table de estágios
=> correção de pendênicas

app/Http/Controllers/VagaController.php, app/Http/Requests/VagaRequest.php, database/factories/VagaFactory.php, database/migrations/2022_08_03_223400_add_justificativa_to_vagas_table.php, database/seeders/VagaSeeder.php, resources/views/vagas/show.blade.php
Ao clicar em "Reprovar" uma vaga, irá abrir um modal com o campo justificativa.
=> Campo justificativa para vagas reprovadas

resources/views/pdfs/termo.blade.php
=> Alterações no termo de ciência (pdf)

app/Http/Controllers/EstagioWorkflowController.php, app/Mail/GerarRescisaoMail.php, resources/views/emails/alteracao_empresa.blade.php, resources/views/emails/gerar_rescisao.blade.php
=> Manda email automático ao pedir rescisão de estágio

app/Http/Controllers/EmailController.php, app/Http/Controllers/GeneralSettingsController.php, app/Mail/enviar_para_estudante_mail.php, app/Service/GeneralSettings.php, resources/views/emails/enviar_para_estudante.blade.php, resources/views/estagios/partials/gerenciar_estagio.blade.php, resources/views/settings/show.blade.php, routes/web.php
Inclusão da função de envio de e-mail contendo o termo para o estudante.
=> Inclusão de Envio de E-mail Estudante

app/Http/Controllers/ReportController.php, resources/views/reports/index.blade.php
Implementação dos filtros de busca Carga Horária e Parecerista na busca dos relatórios
=> Criação dos FIltros de Busca dos Relátorios

resources/views/pdfs/parecer.blade.php
Correção do campo "Horário Compatível de Estágio" que exibia um dado duplicado ao campo de Justificativa.
=> Correção PDF de Parecer de Mérito Externo

app/Utils/ReplicadoUtils.php
tabela "SITALUNOATIVOGR" foi excluída, portanto foi necessária usar join entre duas outras tables.
=> nova query para trazer o período da habilitação do aluno

app/Models/Estagio.php, app/Utils/ReplicadoUtils.php, database/settings/defaults/renovacao.txt, resources/views/pdfs/renovacao.blade.php
Excluindo todas as aparições restantes do semestre do sistema.
Mandado PR para resolver discrepâncias entre o sistema no ar e as máquinas
=> removendo o semestre do aluno do pdf de renovação
